name: "voice_offer_recommendation"
version: "1.0.0"
config-version: 2

profile: "voice_offer_recommendation"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  voice_offer_recommendation:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    feature:
      +materialized: table
      +schema: feature